debug: false
server:
  id: "my-bungee"
storage-container:
  driver: "redis"
  host: "0.0.0.0"
  port: 6379
  password: ""
message-broker:
  driver: "redis"
  host: "0.0.0.0"
  port: 6379
  password: ""